apiVersion: apps/v1
kind: Deployment
metadata:
  name: imptfc
spec:
  selector:
    matchLabels:
      app: imptfc
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: imptfc
    spec:
      #      nodeSelector:
      #        kubernetes.io/hostname: sd-origin
      containers:
      - image: javimosch/mufc-front:1.0
        imagePullPolicy: Always
        name: imptfc
        resources:
         limits:
          cpu: 80m
         requests: 
          cpu: 50m
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        command: ["npm", "run", "start"]
        workingDir: /app
---
apiVersion: v1
kind: Service
metadata:
  name: imptfc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: imptfc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imptfc
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-alt"

spec:
  tls:
  - hosts:
    - mfc.misitioba.com
    secretName: imptfc-secret-tls
  rules:
  - host: mfc.misitioba.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imptfc
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: imptfc-prod
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod-alt"

spec:
  tls:
  - hosts:
    - play.mufc.fr
    secretName: imptfc-prod-secret-tls
  rules:
  - host: play.mufc.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: imptfc
            port:
              number: 80
