version: '3.8'
services:
  playmufc:
    image: javimosch/mufc-front:1.0.9
    container_name: playmufc
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.08'  # 80m
        reservations:
          cpus: '0.05'  # 50m
    ports:
      - "3001:8080"
    environment:
      - NODE_ENV=production
    working_dir: /app
